import mongoose from "mongoose";
const doctorSchema=new mongoose.Schema(
    {
        name:{
            type:String,
            required:true,
            trim:true
        },
        email:{
            type:String,
            required:true,
            unique:true,
            lowercase:true,
            trim:true
        },
        phone_number:{
            type:String,
            required:true,
            unique:true,
            trim:true
        },
        password:{
            type:String,
            required:true
        },
        specialty:{
            type:String,
            required:true,
            trim:true
        },
        license_number:{
            type:String,
            required:true,
            unique:true,
            trim:true
        },
        council:{
            type:String,
            required:true,
            trim:true
        },
        qualification:{
            type:String,
            required:true,
            trim:true
        },
        hospital_id:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Hospital",
            required:true
        },
        govt_document:{
            type:String,
            required:true
        }
    },
    {
        timestamps:true
    }
);       
const Doctor=mongoose.model("Doctor",doctorSchema);
export default Doctor;