import mongoose from "mongoose";
const hospitalSchema=new mongoose.Schema(
    {
        ownershipType:{
            type:String,
            required:true,
            enum:[
                "Government",
                "Private",
                "Trust / NGO",
                "Public-Private Partnership"
            ]
        },
        ownerName:{
            type:String,
            required:true,
            trim:true
        },
        contactName:{
            type:String,
            required:true,
            trim:true
        },
        contactDesignation:{
            type:String,
            trim:true
        },
        contactPhone:{
            type:String,
            required:true,
            trim:true
        },
        contactEmail:{
            type:String,
            required:true,
            lowercase:true,
            trim:true
        },
        password:{
          type:String,
          required:true
        },
        legalName:{
            type:String,
            required:true,
            trim:true
        },
        tradeName:{
            type:String,
            trim:true
        },
        registrationNumber:{
            type:String,
            required:true,
            unique:true,
            trim:true
        },
        issuingAuthority:{
            type:String,
            required:true,
            trim:true
        },
        licenseValidTill:{
            type:Date,
            required:true
        },
        accreditationNumber:{
            type:String,
            trim:true
        },
        cityOrDistrict:{
            type:String,
            required:true,
            trim:true
        },
        state:{
            type:String,
            required:true,
            trim:true
        },
        pinCode:{
            type:String,
            required:true,
            trim:true
        },
        emergencyBeds:{
            type:Number,
            default:0,
            min:0
        },
        availableEmergencyBeds:{
            type:Number,
            default:0,
            min:0
        },
        certificate:{
            type:String
        }
    },
    {
        timestamps:true
    }
);
const Hospital=mongoose.model("Hospital",hospitalSchema);
export default Hospital;